apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "kadalu-storage.handoffAnnotations" . | nindent 2 }}
  name: kadalu-server-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kadalu-storage.labels" . | nindent 4 }}
