annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: use template to generate README.md
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
# renovate: image=ghcr.io/home-operations/sonarr
appVersion: 4.0.19.2995
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts/
  version: 1.5.1
description: Smart PVR for newsgroup and bittorrent users
home: https://github.com/joejulian/charts/tree/main/charts/sonarr
icon: https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/512.png
keywords:
- sonarr
- servarr
- torrent
- usenet
maintainers:
- name: Joe Julian
name: sonarr
sources:
- https://github.com/Sonarr/Sonarr
- https://github.com/home-operations/containers
- https://github.com/pree/helm-charts
type: application
version: 1.12.0
