apiVersion: v2
name: learner
description: Spam learning cron job
type: application
version: 0.1.0
# renovate: image=registry.gitlab.com/joejulian/container-learnspam
appVersion: "latest"
home: https://github.com/joejulian/charts/tree/main/charts/learner
maintainers:
  - name: Joe Julian
    email: me@joejulian.name
sources:
  - https://gitlab.com/joejulian/container-learnspam
