---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-conf
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}"
data:
  nzbget.conf: |
{{ .Values.nzbget.config | indent 4 }}
