{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "stable-diffusion.name" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "stable-diffusion.selector" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.ingressFrom | nindent 8 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress: []
{{- end }}
