apiVersion: v1
kind: Service
metadata:
  name: {{ include "stable-diffusion.name" . }}
  labels:
    {{- include "stable-diffusion.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stable-diffusion.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
