{{- if .Values.config.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfix.configSecretName" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.config.secretData | nindent 2 }}
{{- end }}
