apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - name: smtp
    port: {{ .Values.service.ports.smtp.port }}
    protocol: {{ .Values.service.ports.smtp.protocol }}
    targetPort: {{ .Values.service.ports.smtp.targetPort }}
    {{- with .Values.service.ports.smtp.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  - name: submission
    port: {{ .Values.service.ports.submission.port }}
    protocol: {{ .Values.service.ports.submission.protocol }}
    targetPort: {{ .Values.service.ports.submission.targetPort }}
    {{- with .Values.service.ports.submission.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  {{- with .Values.service.extraPorts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    {{- include "postfix.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
