apiVersion: v2
name: transmission
description: Transmission deployment with optional VPN-oriented settings
type: application
version: 0.1.1
# renovate: image=linuxserver/transmission
appVersion: "latest"
home: https://github.com/joejulian/charts/tree/main/charts/transmission
maintainers:
  - name: Joe Julian
    email: me@joejulian.name
sources:
  - https://github.com/linuxserver/docker-transmission
  - https://github.com/haugene/docker-transmission-openvpn
