annotations:
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
name: unifi-cam-proxy
description: UniFi Protect camera proxy deployment
type: application
version: "0.1.2"
# renovate: image=ghcr.io/joejulian/unifi-cam-proxy
appVersion: "0.3.6"
home: https://github.com/joejulian/charts/tree/main/charts/unifi-cam-proxy
maintainers:
  - name: Joe Julian
    email: me@joejulian.name
sources:
  - https://github.com/joejulian/unifi-cam-proxy
