apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-external-attacher
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-external-attacher
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kadalu-csi-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kadalu-csi-external-attacher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-external-provisioner
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-external-provisioner
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kadalu-csi-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kadalu-csi-external-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-external-resizer
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattributesclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-external-resizer
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kadalu-csi-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kadalu-csi-external-resizer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-nodeplugin
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-nodeplugin
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kadalu-csi-nodeplugin
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kadalu-csi-nodeplugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "kadalu-csi.handoffAnnotations" . | nindent 2 }}
  name: kadalu-csi-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kadalu-csi-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kadalu-csi-leader-election
