apiVersion: v1
kind: ServiceAccount
metadata:
  name: kadalu-csi-nodeplugin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kadalu-csi-provisioner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kadalu-csi.labels" . | nindent 4 }}
