annotations:
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
# renovate: image=ghcr.io/joejulian/kadalu-operator
appVersion: 1.4.0-rc.5
description: Kadalu operator with operator-owned CSI and storage reconciliation
home: https://github.com/joejulian/charts/tree/main/charts/kadalu-operator
maintainers:
  - email: me@joejulian.name
    name: joejulian
name: kadalu-operator
sources:
  - https://github.com/joejulian/kadalu
type: application
version: 0.1.2
