apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.priorityClass.name }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      {{- if .Values.initContainer.enabled }}
      initContainers:
        - name: init
          image: {{ .Values.initContainer.image }}
          command:
            {{- toYaml .Values.initContainer.command | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
      {{- end }}
      containers:
        - name: plex
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: plex
              containerPort: 32400
            - name: plex-udp
              containerPort: 32400
              protocol: UDP
            - name: dlna
              containerPort: 32469
            - name: dlna-udp
              containerPort: 32469
              protocol: UDP
            - name: gdm-5353
              containerPort: 5353
              protocol: UDP
            - name: gdm-1900
              containerPort: 1900
              protocol: UDP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /web/index.html
              port: plex
            initialDelaySeconds: 120
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: codecs
              mountPath: /config/Library/Application Support/Plex Media Server/Codecs
            {{- if .Values.persistence.media.enabled }}
            - name: media
              mountPath: /mnt/media
            {{- end }}
            {{- if .Values.tls.existingSecret }}
            - name: cert
              mountPath: {{ .Values.tls.mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-config" (include "plex.fullname" .)) .Values.persistence.config.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: codecs
          emptyDir: {}
        {{- if .Values.persistence.media.enabled }}
        - name: media
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-media" (include "plex.fullname" .)) .Values.persistence.media.existingClaim }}
        {{- end }}
        {{- if .Values.tls.existingSecret }}
        - name: cert
          secret:
            secretName: {{ .Values.tls.existingSecret }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
