{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.fullname" . }}-config
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.fullname" . }}-media
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.media.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- with .Values.persistence.media.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.persistence.media.volumeName }}
  volumeName: {{ . }}
  {{- end }}
{{- end }}
