annotations:
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
# renovate: image=ghcr.io/joejulian/kadalu-csi
appVersion: 1.4.0-rc.5
description: Kadalu CSI identities, RBAC, and operator-consumed release configuration
home: https://github.com/joejulian/charts/tree/main/charts/kadalu-csi
maintainers:
  - email: me@joejulian.name
    name: joejulian
name: kadalu-csi
sources:
  - https://github.com/joejulian/kadalu
type: application
version: 0.1.1
