annotations:
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
name: plex
description: Plex Media Server chart with GPU, certificate, ingress, and LB options
type: application
version: 0.2.0
# renovate: image=ghcr.io/joejulian/container-images/plex-media-server-plexpass
appVersion: "1.43.1.10561-1"
home: https://github.com/joejulian/charts/tree/main/charts/plex
maintainers:
  - name: Joe Julian
    email: me@joejulian.name
sources:
  - https://github.com/joejulian/container-images
