annotations:
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
name: external-dns
description: ExternalDNS deployment with configurable arguments and RBAC
type: application
version: "0.2.1"
# renovate: image=registry.k8s.io/external-dns/external-dns
appVersion: "v0.20.0"
home: https://github.com/joejulian/charts/tree/main/charts/external-dns
maintainers:
  - name: Joe Julian
    email: me@joejulian.name
sources:
  - https://github.com/kubernetes-sigs/external-dns
