replicaCount: 1

image:
  repository: ghcr.io/joejulian/container-images/external-dns
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

args: []
