apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "minetest.fullname" . }}
  labels:
    app: {{ template "minetest.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "minetest.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "minetest.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-mods
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -e
            - -o
            - pipefail
            - -c
            - |
              [ ! -d /data/worldmods ] || rm -rf /data/worldmods
              while read mod url; do
                [ -n "${mod}" ] || continue
                echo "Installing from ${mod}"
                mkdir -p "/data/worldmods/${mod}"
                wget -O - -q "${url}" | tar -C "/data/worldmods/${mod}" --strip-components=1 -xz
              done < /config/installmods.txt
          volumeMounts:
            - name: data
              mountPath: /data
            - name: mods
              mountPath: /config/installmods.txt
              subPath: installmods.txt
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
{{ toYaml .Values.command | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: data
              mountPath: /data
            - name: world-secret
              mountPath: /data/world.mt
              subPath: {{ .Values.world.secretKey }}
          ports:
            - name: dataport
              containerPort: {{ .Values.service.internalPort }}
              protocol: UDP
          livenessProbe:
            exec:
              command:
                - cat
                - /proc/1/status
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-conf
        - name: data
          persistentVolumeClaim:
              claimName: {{ default (printf "%s-data" .Release.Name) .Values.persistence.existingClaim }}
        - name: world-secret
          secret:
            secretName: {{ .Values.world.existingSecret }}
        - name: mods
          configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-mods
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
