apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "learner.fullname" . }}
  labels:
    {{- include "learner.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "learner.selectorLabels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ include "learner.name" . }}
              image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- range .Values.env }}
                - name: {{ .name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Values.secretName }}
                      key: {{ .secretKey }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: {{ .Values.restartPolicy }}
