{{- include "bjw-s.common.loader.init" . }}
{{- define "sonarr.hardcodedValues" -}}
controllers:
  main:
    containers:
      main:
        image:
          tag: {{ .Values.controllers.main.containers.main.image.tag | default .Chart.AppVersion | quote }}
      {{- if .Values.metrics.enabled }}
      exporter:
        image:
          repository: {{ .Values.metrics.exporter.image.repository }}
          tag: {{ .Values.metrics.exporter.image.tag | quote }}
          pullPolicy: {{ .Values.metrics.exporter.image.pullPolicy }}
        args: ["sonarr"]
        env:
          URL: "http://localhost:8989"
          CONFIG: /config/config.xml
          PORT: {{ .Values.metrics.exporter.env.port | quote }}
          ENABLE_ADDITIONAL_METRICS: {{ .Values.metrics.exporter.env.additionalMetrics | quote }}
          ENABLE_UNKNOWN_QUEUE_ITEMS: {{ .Values.metrics.exporter.env.unknownQueueItems | quote }}
        {{- with .Values.metrics.exporter.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
{{- if .Values.metrics.enabled }}
service:
  metrics:
    enabled: true
    controller: main
    ports:
      metrics:
        enabled: true
        protocol: TCP
        port: {{ .Values.metrics.exporter.env.port }}
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "sonarr.hardcodedValues" . | fromYaml) -}}
{{ include "bjw-s.common.loader.generate" . }}
