{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cyrus-imap.fullname" . }}
  labels:
    {{- include "cyrus-imap.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: {{ .Values.certificate.duration }}
  issuerRef:
    kind: {{ .Values.certificate.issuerRef.kind }}
    name: {{ .Values.certificate.issuerRef.name }}
  dnsNames:
    {{- toYaml .Values.certificate.dnsNames | nindent 4 }}
{{- end }}
