apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cyrus-imap.fullname" . }}
  labels:
    {{- include "cyrus-imap.labels" . | nindent 4 }}
data:
  cyrus.conf: |
{{ .Values.config.cyrusConf | indent 4 }}
  imapd.conf: |
{{ .Values.config.imapdConf | indent 4 }}
