{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cyrus-imap.fullname" . }}-data
  labels:
    {{- include "cyrus-imap.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
