{{- if and .Values.saslauthd.enabled (not .Values.saslauthd.existingConfigSecret) .Values.saslauthd.inlineConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cyrus-imap.fullname" . }}-saslauthd
  labels:
    {{- include "cyrus-imap.labels" . | nindent 4 }}
type: Opaque
stringData:
  saslauthd.conf: |
{{ .Values.saslauthd.inlineConfig | indent 4 }}
{{- end }}
