{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cyrus-imap.serviceAccountName" . }}
  labels:
    {{- include "cyrus-imap.labels" . | nindent 4 }}
{{- end }}
