annotations:
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
# renovate: image=ghcr.io/joejulian/justmount
appVersion: v0.2.10
description: Node-only CSI driver for mounting existing filesystems
home: https://github.com/joejulian/charts/tree/master/charts/justmount
maintainers:
- email: me@joejulian.name
  name: joejulian
name: justmount
sources:
- https://github.com/joejulian/csi-justmount
type: application
version: "0.2.10"
