apiVersion: v2
name: openldap
version: 0.0.6
# renovate: image=registry.gitlab.com/joejulian/image-openldap
appVersion: "57ded59212435c138a822aa384b8825c87846af9"
description: OpenLDAP chart
keywords:
- openldap
home: https://github.com/joejulian/charts/tree/master/charts/openldap
sources:
- https://gitlab.com/joejulian/chart-openldap
maintainers:
- name: Joe Julian
  email: me@joejulian.name
type: application
