# Default values for openldap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
fullnameOverride: ""
selectorLabels: {}
podLabels: {}
deploymentName: ""
containerName: openldap
args: []
dataMountPath: /data
initContainer:
  image: ghcr.io/containerd/busybox:1.36
image:
  repository: registry.gitlab.com/joejulian/image-openldap
  tag: ""
  pullPolicy: Always
service:
  resourceName: ""
  name: ldap
  type: ClusterIP
  externalPort: 389
  internalPort: 10389
  nodePort: null
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
configfiles:
  slapd.conf: |
    include		/etc/openldap/schema/core.schema
    pidfile		/run/openldap/slapd.pid
    argsfile	/run/openldap/slapd.args
    database	mdb
    maxsize		1073741824
    suffix		"dc=my-domain,dc=com"
    rootdn		"cn=Manager,dc=my-domain,dc=com"
    rootpw		secret
    directory	/data/data
    index	objectClass	eq
configdb:
  enabled: false
  data: {}

persistence:
  enabled: true
  existingClaim: ""
  size: 3Gi

nodeSelector: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
