apiVersion: v2
name: nzbget
description: An nzbget chart for Kubernetes
version: 0.0.6
# renovate: image=registry.gitlab.com/joejulian/nzbget-docker
appVersion: "latest"
keywords:
  - nzbget
home: https://github.com/joejulian/charts/tree/master/charts/nzbget
sources:
  - https://gitlab.com/joejulian/nzbget-docker
  - https://github.com/nzbget
maintainers:
  - name: Joe Julian
    email: me@joejulian.name
type: application
