{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transmission.fullname" . }}-config
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transmission.fullname" . }}-media
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.media.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
{{- end }}
