annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: use template to generate README.md
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v2
# renovate: image=ghcr.io/home-operations/radarr
appVersion: 6.4.2.10590
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts/
  version: 1.5.1
description: A fork of Sonarr to work with movies à la Couchpotato
home: https://github.com/joejulian/charts/tree/main/charts/radarr
icon: https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/512.png
keywords:
- radarr
- servarr
- torrent
- usenet
maintainers:
- name: Joe Julian
name: radarr
sources:
- https://github.com/Radarr/Radarr
- https://github.com/home-operations/containers
- https://github.com/pree/helm-charts
type: application
version: 1.28.1
