apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default (include "openldap.fullname" .) .Values.deploymentName }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- if .Values.selectorLabels }}
{{ toYaml .Values.selectorLabels | indent 6 }}
      {{- else }}
      app: {{ template "openldap.name" . }}
      release: {{ .Release.Name }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- if .Values.selectorLabels }}
{{ toYaml .Values.selectorLabels | indent 8 }}
        {{- else }}
        app: {{ template "openldap.name" . }}
        release: {{ .Release.Name }}
        {{- end }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ if .Values.args }}
          args:
{{ toYaml .Values.args | indent 12 }}
{{ else if not .Values.configfiles }}
          args:
            - -F
            - {{ .Values.dataMountPath }}/config
{{ end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.dataMountPath }}
{{ if .Values.configfiles }}
            - name: config
              mountPath: /config
{{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ default (include "openldap.name" .) .Values.persistence.existingClaim }}
{{ if .Values.configfiles }}
        - name: config
          configMap:
            name: {{ template "openldap.name" . }}
{{ end }}
{{ if .Values.configdb.enabled }}
        - name: initdata
          secret:
            name: {{ template "openldap.name" . }}
{{ end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
