apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "openldap.fullname" .) .Values.service.resourceName }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
{{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{ end }}
  selector:
{{ if .Values.selectorLabels }}
{{ toYaml .Values.selectorLabels | indent 4 }}
{{ else }}
    app: {{ template "openldap.name" . }}
    release: {{ .Release.Name }}
{{ end }}
