annotations:
  org.opencontainers.image.source: https://github.com/joejulian/charts
apiVersion: v1
description: A Helm chart for running a Luanti server
name: luanti
# renovate: image=ghcr.io/joejulian/container-images/minetest
appVersion: "5.15.0-r1"
home: https://github.com/joejulian/charts/tree/main/charts/luanti
maintainers:
  - name: Joe Julian
    email: me@joejulian.name
sources:
  - https://github.com/luanti-org/luanti
version: 0.0.1
