annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: use template to generate README.md
apiVersion: v2
# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: 2025.12.5
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts/
  version: ~4
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 16.7.24
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 22.0.0
- condition: influxdb.enabled
  name: influxdb
  repository: https://charts.bitnami.com/bitnami
  version: 7.1.15
description: Open source home automation that puts local control and privacy first
home: https://github.com/pree/helm-charts/tree/master/charts/home-assistant
icon: https://raw.githubusercontent.com/home-assistant/home-assistant.io/current/source/images/favicon-192x192.png
keywords:
- home-assistant
- hass
- homeassistant
- smarthome
maintainers:
- email: pascal@reeb.io
  name: pree
name: home-assistant
sources:
- https://github.com/home-assistant/core
type: application
version: 2.0.0
